### PR TITLE
Setting cross-compile flag in CI file

### PR DESCRIPTION
**Pull request by ifkb99**
fixing #96

### CODE REVIEW

**Comment by dvc94ch** [comment]
Can you reenable building http on cross targets?

**Comment by dvc94ch** [comment]
Mmh, can you try rebasing again? Looks like something went wrong

**Comment by ifkb99** [comment]
I'm going to try and sort this out

**Comment by aphelionz** [comment]
@ifkb99 Don't give up! Let me know if I can help at all.

**Pull request closed without merging**
